apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: backend
    spec:
      containers:
        - env:
            - name: DB_HOST
              value: db
            - name: DB_NAME
              value: smartdocs
            - name: DB_PASSWORD
              value: smartpass
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              value: smartuser
            - name: OLLAMA_API
              value: http://ollama:11434
            - name: OLLAMA_MODEL
              value: llama3:8b-instruct-q4_0
          image: backend
          name: smartdocs-backend
          ports:
            - containerPort: 8000
              protocol: TCP
      restartPolicy: Always
