apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: clamav
  name: clamav
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: clamav
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: clamav
    spec:
      containers:
        - env:
            - name: CLAMAV_NO_FRESHCLAMD
              value: "true"
          image: clamav/clamav:latest
          livenessProbe:
            exec:
              command:
                - clamdscan
                - --version
            failureThreshold: 3
            periodSeconds: 30
            timeoutSeconds: 10
          name: clamav
          volumeMounts:
            - mountPath: /var/lib/clamav
              name: clamav-data
      restartPolicy: Always
      volumes:
        - name: clamav-data
          persistentVolumeClaim:
            claimName: clamav-data
