FROM python:3.10-slim
WORKDIR /app/src 

# Instala dependencias...
RUN apt-get update && apt-get install -y \
    gcc python3-dev libmagic-dev default-libmysqlclient-dev && rm -rf /var/lib/apt/lists/*

# Copia requirements.txt a /app/src
COPY src/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copia todo el código a /app/src
COPY src/ .

# Configura PYTHONPATH para que incluya /app/src
ENV PYTHONPATH=/app/src

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
